# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 687d89d2080aa8d069840cd39d3a45bbd31490b01539fb3b6e6bbc4ebc9d3616cdeb68ab7b332f793439b65c00929a16c94d5983e4f1b909cb92fa86b6f53633

test:
  secret_key_base: 88573838e8228f8281d3fe8ce4a16985cf54e6522804c97ff82ef2d5b2637efbc387a45ce9bd9dcc859b43c8b5df657656942f7bd87eb94964419da4a910877b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
